# Generated by Django 2.2.4 on 2019-08-13 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photocateg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('hairstyle', 'Hairstyle'), ('makeup', 'Makeup'), ('hair color', 'Hair Color')], default='hairstyle', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Optional Title')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded On')),
                ('jpg_photo', models.ImageField(default='default-blog.jpg', upload_to='gallery_jpg')),
                ('web_photo', models.ImageField(default='default-blog.jpg', upload_to='gallery_webp')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_content.Photocateg')),
            ],
        ),
    ]
