# Generated by Django 2.2.4 on 2019-08-30 23:03

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photocateg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('haircut', 'Haircut'), ('hairstyle', 'Hairstyle'), ('makeup', 'Makeup'), ('hair color', 'Hair Color')], default='hairstyle', max_length=10)),
            ],
            options={
                'verbose_name': 'Photo Category',
                'verbose_name_plural': 'Photo Categories',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo_full', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('photo_thumb', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted On')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_content.Photocateg')),
            ],
        ),
    ]
