# Generated by Django 2.2.1 on 2019-06-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
