# Generated by Django 2.2.4 on 2019-08-13 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='jpg_photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='web_photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted On'),
        ),
        migrations.AddField(
            model_name='photo',
            name='post_photo',
            field=models.ImageField(default='default-blog.jpg', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
