# Generated by Django 2.2.4 on 2019-08-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_1500_jpg',
            field=models.ImageField(default='default-blog.jpg', upload_to='gallery/jpg/1500'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_1500_webp',
            field=models.ImageField(default='default-blog.webp', upload_to='gallery/webp/1500'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_400_jpg',
            field=models.ImageField(default='default-blog.jpg', upload_to='gallery/jpg/400'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_400_webp',
            field=models.ImageField(default='default-blog.webp', upload_to='gallery/webp/400'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_750_jpg',
            field=models.ImageField(default='default-blog.jpg', upload_to='gallery/jpg/750'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_750_webp',
            field=models.ImageField(default='default-blog.webp', upload_to='gallery/webp/750'),
        ),
    ]
