# Generated by Django 2.2.4 on 2019-08-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_auto_20190818_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_1500_jpg',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_1500_webp',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_400_jpg',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_400_webp',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_750_jpg',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_750_webp',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_full',
            field=models.ImageField(default='default-blog.jpg', upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_thumbnail',
            field=models.ImageField(default='default-blog.jpg', upload_to='gallery/thumbnails'),
        ),
    ]
