# Generated by Django 2.2.4 on 2019-08-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_auto_20190818_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocateg',
            name='category',
            field=models.CharField(choices=[('haircut', 'Haircut'), ('hairstyle', 'Hairstyle'), ('makeup', 'Makeup'), ('hair color', 'Hair Color')], default='hairstyle', max_length=10),
        ),
    ]
