# Generated by Django 2.2.4 on 2019-08-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_auto_20190813_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='webp_photo',
        ),
    ]
