# Generated by Django 2.2.4 on 2019-08-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0004_remove_photo_webp_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='jpg_photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='default-blog.jpg', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='photocateg',
            name='category',
            field=models.CharField(choices=[('hairstyle', 'Hairstyle'), ('makeup', 'Makeup'), ('hair color', 'Hair Color')], default='hairstyle', max_length=10),
        ),
    ]
