# Generated by Django 2.2.4 on 2019-08-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_photo_webp',
            field=models.ImageField(default='default-blog.webp', upload_to='post_photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('hairstyle', 'Hairstyle'), ('makeup', 'Makeup'), ('hair color', 'Hair Color'), ('haircut', 'Haircut'), ('hair care', 'Hair Care')], default='hairstyle', max_length=10),
        ),
    ]
