# Generated by Django 2.2.1 on 2019-06-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190609_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
