# Generated by Django 2.2.1 on 2019-08-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190731_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Hairstyle', 'Hairstyle'), ('Makeup', 'Makeup')], default='Hairstyle', max_length=10)),
            ],
        ),
    ]
