# Generated by Django 2.2.1 on 2019-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='posts',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
