# Generated by Django 2.2.1 on 2019-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postcategory_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='postcategory',
            field=models.ManyToManyField(to='blog.PostCategory'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Hairstyle', 'Hairstyle'), ('Makeup', 'Makeup')], default='Hairstyle', max_length=15),
        ),
    ]
