# Generated by Django 2.2.1 on 2019-08-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190804_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(default='default-blog.jpg', upload_to='post_photo'),
        ),
    ]
