# Generated by Django 2.2.1 on 2019-08-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190806_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('personal', 'personal'), ('hairstyle', 'hairstyle'), ('makeup', 'makeup')], default='hairstyle', max_length=15),
        ),
    ]
