# Generated by Django 2.2.1 on 2019-08-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190806_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('pers', 'Personal'), ('hair', 'Hairstyle'), ('make', 'Makeup')], default='hair', max_length=4),
        ),
    ]
